<?php
/**
 * CatalogDataProductCustomOptionInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Community
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CatalogDataProductCustomOptionInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description 
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CatalogDataProductCustomOptionInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CatalogDataProductCustomOptionInterface"
     */
    public function testCatalogDataProductCustomOptionInterface()
    {

    }

    /**
     * Test attribute "product_sku"
     */
    public function testPropertyProductSku()
    {

    }

    /**
     * Test attribute "option_id"
     */
    public function testPropertyOptionId()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "sort_order"
     */
    public function testPropertySortOrder()
    {

    }

    /**
     * Test attribute "is_require"
     */
    public function testPropertyIsRequire()
    {

    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {

    }

    /**
     * Test attribute "price_type"
     */
    public function testPropertyPriceType()
    {

    }

    /**
     * Test attribute "sku"
     */
    public function testPropertySku()
    {

    }

    /**
     * Test attribute "file_extension"
     */
    public function testPropertyFileExtension()
    {

    }

    /**
     * Test attribute "max_characters"
     */
    public function testPropertyMaxCharacters()
    {

    }

    /**
     * Test attribute "image_size_x"
     */
    public function testPropertyImageSizeX()
    {

    }

    /**
     * Test attribute "image_size_y"
     */
    public function testPropertyImageSizeY()
    {

    }

    /**
     * Test attribute "values"
     */
    public function testPropertyValues()
    {

    }

    /**
     * Test attribute "extension_attributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

}
