<?php
/**
 * CmsDataPageInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Community
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CmsDataPageInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description CMS page interface.
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CmsDataPageInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CmsDataPageInterface"
     */
    public function testCmsDataPageInterface()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "identifier"
     */
    public function testPropertyIdentifier()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "page_layout"
     */
    public function testPropertyPageLayout()
    {

    }

    /**
     * Test attribute "meta_title"
     */
    public function testPropertyMetaTitle()
    {

    }

    /**
     * Test attribute "meta_keywords"
     */
    public function testPropertyMetaKeywords()
    {

    }

    /**
     * Test attribute "meta_description"
     */
    public function testPropertyMetaDescription()
    {

    }

    /**
     * Test attribute "content_heading"
     */
    public function testPropertyContentHeading()
    {

    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {

    }

    /**
     * Test attribute "creation_time"
     */
    public function testPropertyCreationTime()
    {

    }

    /**
     * Test attribute "update_time"
     */
    public function testPropertyUpdateTime()
    {

    }

    /**
     * Test attribute "sort_order"
     */
    public function testPropertySortOrder()
    {

    }

    /**
     * Test attribute "layout_update_xml"
     */
    public function testPropertyLayoutUpdateXml()
    {

    }

    /**
     * Test attribute "custom_theme"
     */
    public function testPropertyCustomTheme()
    {

    }

    /**
     * Test attribute "custom_root_template"
     */
    public function testPropertyCustomRootTemplate()
    {

    }

    /**
     * Test attribute "custom_layout_update_xml"
     */
    public function testPropertyCustomLayoutUpdateXml()
    {

    }

    /**
     * Test attribute "custom_theme_from"
     */
    public function testPropertyCustomThemeFrom()
    {

    }

    /**
     * Test attribute "custom_theme_to"
     */
    public function testPropertyCustomThemeTo()
    {

    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {

    }

}
