<?php
/**
 * QuoteDataShippingMethodInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Community
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * QuoteDataShippingMethodInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Interface ShippingMethodInterface
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QuoteDataShippingMethodInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "QuoteDataShippingMethodInterface"
     */
    public function testQuoteDataShippingMethodInterface()
    {

    }

    /**
     * Test attribute "carrier_code"
     */
    public function testPropertyCarrierCode()
    {

    }

    /**
     * Test attribute "method_code"
     */
    public function testPropertyMethodCode()
    {

    }

    /**
     * Test attribute "carrier_title"
     */
    public function testPropertyCarrierTitle()
    {

    }

    /**
     * Test attribute "method_title"
     */
    public function testPropertyMethodTitle()
    {

    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {

    }

    /**
     * Test attribute "base_amount"
     */
    public function testPropertyBaseAmount()
    {

    }

    /**
     * Test attribute "available"
     */
    public function testPropertyAvailable()
    {

    }

    /**
     * Test attribute "extension_attributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

    /**
     * Test attribute "error_message"
     */
    public function testPropertyErrorMessage()
    {

    }

    /**
     * Test attribute "price_excl_tax"
     */
    public function testPropertyPriceExclTax()
    {

    }

    /**
     * Test attribute "price_incl_tax"
     */
    public function testPropertyPriceInclTax()
    {

    }

}
