<?php
/**
 * QuoteDataTotalsItemInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Community
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * QuoteDataTotalsItemInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Interface TotalsItemInterface
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QuoteDataTotalsItemInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "QuoteDataTotalsItemInterface"
     */
    public function testQuoteDataTotalsItemInterface()
    {

    }

    /**
     * Test attribute "item_id"
     */
    public function testPropertyItemId()
    {

    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {

    }

    /**
     * Test attribute "base_price"
     */
    public function testPropertyBasePrice()
    {

    }

    /**
     * Test attribute "qty"
     */
    public function testPropertyQty()
    {

    }

    /**
     * Test attribute "row_total"
     */
    public function testPropertyRowTotal()
    {

    }

    /**
     * Test attribute "base_row_total"
     */
    public function testPropertyBaseRowTotal()
    {

    }

    /**
     * Test attribute "row_total_with_discount"
     */
    public function testPropertyRowTotalWithDiscount()
    {

    }

    /**
     * Test attribute "tax_amount"
     */
    public function testPropertyTaxAmount()
    {

    }

    /**
     * Test attribute "base_tax_amount"
     */
    public function testPropertyBaseTaxAmount()
    {

    }

    /**
     * Test attribute "tax_percent"
     */
    public function testPropertyTaxPercent()
    {

    }

    /**
     * Test attribute "discount_amount"
     */
    public function testPropertyDiscountAmount()
    {

    }

    /**
     * Test attribute "base_discount_amount"
     */
    public function testPropertyBaseDiscountAmount()
    {

    }

    /**
     * Test attribute "discount_percent"
     */
    public function testPropertyDiscountPercent()
    {

    }

    /**
     * Test attribute "price_incl_tax"
     */
    public function testPropertyPriceInclTax()
    {

    }

    /**
     * Test attribute "base_price_incl_tax"
     */
    public function testPropertyBasePriceInclTax()
    {

    }

    /**
     * Test attribute "row_total_incl_tax"
     */
    public function testPropertyRowTotalInclTax()
    {

    }

    /**
     * Test attribute "base_row_total_incl_tax"
     */
    public function testPropertyBaseRowTotalInclTax()
    {

    }

    /**
     * Test attribute "options"
     */
    public function testPropertyOptions()
    {

    }

    /**
     * Test attribute "weee_tax_applied_amount"
     */
    public function testPropertyWeeeTaxAppliedAmount()
    {

    }

    /**
     * Test attribute "weee_tax_applied"
     */
    public function testPropertyWeeeTaxApplied()
    {

    }

    /**
     * Test attribute "extension_attributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

}
