<?php
/**
 * QuoteDataCartInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Community
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * QuoteDataCartInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Interface CartInterface
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QuoteDataCartInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "QuoteDataCartInterface"
     */
    public function testQuoteDataCartInterface()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {

    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {

    }

    /**
     * Test attribute "converted_at"
     */
    public function testPropertyConvertedAt()
    {

    }

    /**
     * Test attribute "is_active"
     */
    public function testPropertyIsActive()
    {

    }

    /**
     * Test attribute "is_virtual"
     */
    public function testPropertyIsVirtual()
    {

    }

    /**
     * Test attribute "items"
     */
    public function testPropertyItems()
    {

    }

    /**
     * Test attribute "items_count"
     */
    public function testPropertyItemsCount()
    {

    }

    /**
     * Test attribute "items_qty"
     */
    public function testPropertyItemsQty()
    {

    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {

    }

    /**
     * Test attribute "billing_address"
     */
    public function testPropertyBillingAddress()
    {

    }

    /**
     * Test attribute "reserved_order_id"
     */
    public function testPropertyReservedOrderId()
    {

    }

    /**
     * Test attribute "orig_order_id"
     */
    public function testPropertyOrigOrderId()
    {

    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {

    }

    /**
     * Test attribute "customer_is_guest"
     */
    public function testPropertyCustomerIsGuest()
    {

    }

    /**
     * Test attribute "customer_note"
     */
    public function testPropertyCustomerNote()
    {

    }

    /**
     * Test attribute "customer_note_notify"
     */
    public function testPropertyCustomerNoteNotify()
    {

    }

    /**
     * Test attribute "customer_tax_class_id"
     */
    public function testPropertyCustomerTaxClassId()
    {

    }

    /**
     * Test attribute "store_id"
     */
    public function testPropertyStoreId()
    {

    }

    /**
     * Test attribute "extension_attributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

}
