<?php
/**
 * StoreDataStoreConfigInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Community
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StoreDataStoreConfigInterfaceTest Class Doc Comment
 *
 * @category    Class */
// * @description StoreConfig interface
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StoreDataStoreConfigInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "StoreDataStoreConfigInterface"
     */
    public function testStoreDataStoreConfigInterface()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {

    }

    /**
     * Test attribute "website_id"
     */
    public function testPropertyWebsiteId()
    {

    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {

    }

    /**
     * Test attribute "base_currency_code"
     */
    public function testPropertyBaseCurrencyCode()
    {

    }

    /**
     * Test attribute "default_display_currency_code"
     */
    public function testPropertyDefaultDisplayCurrencyCode()
    {

    }

    /**
     * Test attribute "timezone"
     */
    public function testPropertyTimezone()
    {

    }

    /**
     * Test attribute "weight_unit"
     */
    public function testPropertyWeightUnit()
    {

    }

    /**
     * Test attribute "base_url"
     */
    public function testPropertyBaseUrl()
    {

    }

    /**
     * Test attribute "base_link_url"
     */
    public function testPropertyBaseLinkUrl()
    {

    }

    /**
     * Test attribute "base_static_url"
     */
    public function testPropertyBaseStaticUrl()
    {

    }

    /**
     * Test attribute "base_media_url"
     */
    public function testPropertyBaseMediaUrl()
    {

    }

    /**
     * Test attribute "secure_base_url"
     */
    public function testPropertySecureBaseUrl()
    {

    }

    /**
     * Test attribute "secure_base_link_url"
     */
    public function testPropertySecureBaseLinkUrl()
    {

    }

    /**
     * Test attribute "secure_base_static_url"
     */
    public function testPropertySecureBaseStaticUrl()
    {

    }

    /**
     * Test attribute "secure_base_media_url"
     */
    public function testPropertySecureBaseMediaUrl()
    {

    }

    /**
     * Test attribute "extension_attributes"
     */
    public function testPropertyExtensionAttributes()
    {

    }

}
